name: Missing API docs
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    branches-ignore:
      - 'marvim/api-doc-update**'

jobs:
  call-regen-api-docs:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/api-docs.yml
